language: java
jdk: oraclejdk11

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - denshmain@gmail.com
    on_success: always # default: change
    on_failure: always # default: always